name: Checkpoint migrations

on: 
  pull_request:
    branches:
      - main
    paths:
      - '.release-please-manifest.json'
    types: [opened, synchronize, reopened]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - run: |
          VERSION=$(jq -r '."."' .release-please-manifest.json)
          MIGRATION_FOLDER=src/test-package/migrations

          echo "Next version: $VERSION"

          find $MIGRATION_FOLDER -type f -name "*.py" -print0 | while IFS= read -r -d '' file; do
            if grep -q '%NEXT_ANEMOI_MODELS_VERSION%' "$file"; then
              sed -i "s/%NEXT_ANEMOI_MODELS_VERSION%/$VERSION/g" "$file"
              echo " + Updated $file"
            fi
          done

          echo "$(git diff)"
          
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git add .
            git commit -m "checkpoint migrations"
            git push
          fi